services:
  app:
    build: .
    container_name: lumina_project_v2
    restart: unless-stopped
    ports:
      - "4205:4205"
    environment:
      - PORT=4205
      - DATABASE_URL=file:./data/lumina_v2.db
      - JWT_SECRET=lumina_jwt_secret_2025_super_strong_key_v2
    volumes:
      - lumina_sqlite_data_v2:/app/data

volumes:
  lumina_sqlite_data_v2:
