services:
  app:
    build: .
    container_name: lumina_project
    restart: unless-stopped
    ports:
      - "4102:4102"
    environment:
      - PORT=4102
      - DATABASE_URL=file:./data/database.db
      - JWT_SECRET=sua_chave_secreta_lumina_muito_forte_e_segura
    volumes:
      - sqlite_data:/app/data

volumes:
  sqlite_data:
